# -*- coding: utf-8 -*-
"""Convert reviewed German locale to Dutch with manual phrase map."""

from __future__ import annotations

import json
import re
from pathlib import Path

SRC_ROOT = Path(__file__).resolve().parent.parent
DE = json.loads((SRC_ROOT / "locales/de.json").read_text(encoding="utf-8"))

# Key-level overrides (native Dutch, not literal DE translation)
KEY_OVERRIDES: dict[str, str] = {
    "account.addSubtitle": "Maak een nieuw account voor dit platform",
    "account.apiHash": "API-hash",
    "account.apiHashHint": "(gemaskeerd in de interface)",
    "account.apiId": "API-ID",
    "account.apiKeys": "API-sleutels",
    "account.createKey": "API-sleutel aanmaken",
    "account.credentialsNote": "API-gegevens worden versleuteld opgeslagen. Hash wordt gemaskeerd in de interface.",
    "account.default": "Als standaard instellen",
    "account.defaultBadge": "Standaard",
    "account.loading": "Accounts laden…",
    "account.logout": "Uitloggen",
    "account.namePlaceholder": "bijv. Werk WhatsApp",
    "account.noAccountsHint": "Geen accounts — tik op + om toe te voegen",
    "account.noAccountsHtml": "Nog geen accounts.",
    "account.saveCredentials": "API-gegevens opslaan",
    "account.subtitle": "Beheer Telegram en WhatsApp hier.",
    "account.switch": "Wisselen",
    "account.switchTo": "Naar dit account wisselen",
    "account.waLinkDesc": "Koppel via QR. Chats en geschiedenis worden automatisch gesynchroniseerd.",
    "account.waStatChats": "{count} chats",
    "account.waStatMsgs": "{count} berichten",
    "brand.tagline": "Telegram & WhatsApp · één paneel",
    "chats.importHint": "Chats verschijnen direct; berichten laden op de achtergrond",
    "chats.noChatsConnect": "Geen chats — verbind je account",
    "chats.searchPlaceholder": "Zoek op naam of nummer…",
    "chats.selectChat": "Selecteer een chat",
    "chats.subtitle": "Bekijk geschiedenis, zoek en antwoord.",
    "chats.waBannerDesc": "Scan QR om chats te zien",
    "common.addAccount": "Account toevoegen",
    "common.done": "Klaar",
    "common.go": "Gaan",
    "common.panel": "Paneel",
    "common.skip": "Overslaan",
    "compose.emptyHint": "Verbind eerst je account of zoek.",
    "compose.recent": "Recent:",
    "compose.searchRecipient": "Ontvanger zoeken…",
    "compose.sendNow": "Nu versturen",
    "compose.title": "Nieuw bericht",
    "compose.to": "Aan",
    "confirm.cancelJob": "Deze taak annuleren?",
    "confirm.deleteAccount": "Dit account verwijderen?",
    "confirm.removeAccount": "Account \"{name}\" verwijderen?",
    "confirm.telegramLogout": "Uitloggen bij Telegram?",
    "confirm.waDisconnect": "WhatsApp verbreken?",
    "dashboard.nextRun": "Volgende verzending (lokale TZ)",
    "dashboard.nextSendTitle": "Volgende verzending",
    "dashboard.noScheduled": "Geen actieve geplande berichten.",
    "dashboard.pending": "In afwachting",
    "dashboard.quickActions": "Snelle acties",
    "dashboard.scheduler": "Planner",
    "dashboard.subtitle": "Volg je berichtactiviteit in één oogopslag.",
    "dashboard.timezone": "Lokale tijdzone",
    "dashboard.viewChats": "Chats bekijken",
    "dashboard.waitingConnect": "Wacht op verbinding",
    "developer.apiDocs": "API-documentatie",
    "developer.noApiKeys": "Nog geen API-sleutels.",
    "developer.noWebhooks": "Nog geen webhooks.",
    "developer.subtitle": "REST API v1, webhooks, automatisering.",
    "developer.title": "Ontwikkelaar & API",
    "empty.connectAccount": "Verbind eerst je account",
    "empty.noAccounts": "Nog geen accounts",
    "empty.selectChat": "Selecteer een chat",
    "enum.repeat.custom": "Aangepast interval",
    "enum.repeat.random_daily": "Dagelijks willekeurig",
    "enum.status.pending": "In afwachting",
    "error.generic": "Er ging iets mis",
    "error.mediaSend": "Media kon niet worden verzonden",
    "footer.api": "API-docs",
    "import.loadingChats": "Chatlijst laden…",
    "lang.select": "Taal selecteren",
    "login.passwordFair": "Redelijke sterkte",
    "login.passwordHint": "Minimaal 8 tekens, letters en cijfers",
    "login.passwordMismatch": "Wachtwoorden komen niet overeen",
    "login.passwordTooWeak": "Kies een sterker wachtwoord (letters + cijfers, min. 8)",
    "login.passwordWeak": "Zwak wachtwoord",
    "login.privacy1": "API-sleutels en sessies worden versleuteld opgeslagen",
    "login.privacy2": "Telefoonnummers worden gemaskeerd in de interface",
    "login.privacy3": "Uitgaande berichten geblokkeerd in testmodus",
    "login.privacy4": "Gegevens blijven alleen op jouw server",
    "login.privacyTitle": "Gegevensbeveiliging",
    "login.setupSubmit": "Account aanmaken",
    "login.setupSubtitle": "Maak een beheerdersaccount. Kies een sterk wachtwoord.",
    "login.setupTitle": "Eerste installatie",
    "login.submit": "Inloggen",
    "login.subtitle": "Log in om door te gaan.",
    "login.title": "Paneel-login",
    "login.username": "Gebruikersnaam",
    "meta.description": "Self-hosted unified inbox voor Telegram en WhatsApp — planning, media, API.",
    "nav.mainMenu": "Hoofdmenu",
    "nav.scheduled": "Gepland",
    "nav.scheduledShort": "Plan",
    "nav.templates": "Sjablonen",
    "onboarding.api": "API & automatisering",
    "onboarding.apiDesc": "Maak API-sleutels en webhooks in Ontwikkelaarstools. Docs op /docs",
    "onboarding.connect": "Accounts verbinden",
    "onboarding.connectDesc": "Koppel Telegram API of scan WhatsApp QR via het tabblad Account.",
    "onboarding.welcome": "Welkom bij Message Panel",
    "onboarding.welcomeDesc": "Beheer Telegram en WhatsApp vanuit één paneel — berichten, media en planning.",
    "setup.accountNameTitle": "Geef dit account een naam",
    "setup.bannerDesc": "Koppel Telegram of WhatsApp — daarna kun je berichten versturen, plannen en chats synchroniseren.",
    "setup.bannerTitle": "Verbind een account om te beginnen",
    "setup.continueConnect": "Doorgaan naar verbinding",
    "setup.firstAccountDesc": "Koppel Telegram of WhatsApp om het paneel te gebruiken.",
    "setup.firstAccountTitle": "Verbind je eerste account",
    "setup.later": "Doe ik later",
    "setup.openingAccount": "Verbindingsscherm openen…",
    "setup.pickPlatform": "Kies een platform",
    "setup.telegramDesc": "API-gegevens en telefoonverificatie",
    "setup.whatsappDesc": "Scan QR-code met je telefoon",
    "platform.telegram.accountHint": "API-gegevens en Telegram-sessie",
    "platform.telegram.chatsSubtitle": "Contacten, groepen en kanalen — geschiedenis en antwoorden.",
    "platform.telegram.chatsTitle": "Telegram-chats",
    "platform.telegram.composeSubtitle": "Kies Telegram-ontvanger, schrijf bericht, verstuur of plan.",
    "platform.whatsapp.accountHint": "WhatsApp Web-verbinding via QR-code",
    "platform.whatsapp.chatsSubtitle": "Contacten en groepen — zoeken en geschiedenis synchroniseren.",
    "platform.whatsapp.chatsTitle": "WhatsApp-chats",
    "platform.whatsapp.composeSubtitle": "Kies WhatsApp-ontvanger, schrijf bericht, verstuur of plan.",
    "prompt.apiKeyName": "Naam API-sleutel:",
    "prompt.apiKeySave": "Bewaar je API-sleutel (eenmalig getoond):",
    "prompt.webhookName": "Webhooknaam:",
    "rename.phoneHint": "Nummer: {phone} — bijv. Mama, Werk",
    "rename.placeholder": "bijv. Mama",
    "rename.title": "Chat hernoemen",
    "safeMode.banner": "Testmodus: uitgaande berichten uitgeschakeld — er wordt niets verzonden.",
    "schedule.modalTitle": "Verzending plannen",
    "schedule.pickWindow": "Selecteer een tijdvenster",
    "schedule.presetEvening": "Vanavond",
    "schedule.presetTomorrow": "Morgen 09:00",
    "schedule.quickSelect": "Snelle keuze",
    "schedule.randomDailySummary": "Dagelijks willekeurig tussen {start}–{end}",
    "schedule.randomHint": "Elke dag een andere tijd binnen je venster.",
    "schedule.randomWindow": "Willekeurig tijdvenster",
    "schedule.relativeRandom": "Eerste verzendtijd bij opslaan · elke volgende dag een andere tijd",
    "schedule.repeatCustom": "Aangepast",
    "schedule.repeatRandom": "Dagelijks willekeurig",
    "schedule.title": "Verzending plannen",
    "schedule.windowError": "Eindtijd moet na starttijd liggen",
    "schedule.windowMorning": "Ochtend 07:00–07:30",
    "scheduled.empty": "Nog geen geplande berichten",
    "scheduled.emptyPlatform": "Nog geen geplande berichten voor {platform}",
    "scheduled.filterPending": "In afwachting",
    "scheduled.newSchedule": "+ Nieuwe planning",
    "scheduled.scheduleFirst": "Eerste bericht plannen",
    "scheduled.sendNow": "Nu versturen",
    "scheduled.sendNowBtn": "Nu versturen",
    "scheduled.subtitle": "Je geplande verzendingen",
    "scheduled.titleFull": "Geplande berichten",
    "scheduled.upcoming": "Binnenkort ({count})",
    "status.checking": "Controleren...",
    "status.disconnected": "Verbroken",
    "status.offline": "Bridge offline",
    "status.qr": "QR in afwachting",
    "status.reconnecting": "Opnieuw verbinden",
    "status.schedulerOff": "Uit",
    "templates.body": "Berichttekst",
    "templates.bodyPlaceholder": "Sjabloontekst…",
    "templates.empty": "Nog geen sjablonen",
    "templates.name": "Sjabloonnaam",
    "templates.newTitle": "Nieuw sjabloon",
    "templates.noneShort": "Nog geen sjablonen",
    "templates.save": "Sjabloon opslaan",
    "templates.savedTitle": "Opgeslagen sjablonen",
    "templates.select": "Sjabloon selecteren…",
    "templates.subtitle": "Bewaar veelgebruikte berichten.",
    "templates.titleFull": "Berichtsjablonen",
    "templates.titleLabel": "Titel",
    "templates.titlePlaceholder": "bijv. Ochtendmededeling",
    "test.safeMode": "Testmodus: bericht niet verzonden (veilig)",
    "theme.dark": "Donker thema",
    "theme.light": "Licht thema",
    "time.daysLater": "over {days} dagen",
    "time.hoursLater": "over {hours} u",
    "time.past": "Tijd in het verleden",
    "time.soon": "Binnenkort verzenden",
    "toast.credentialsSaved": "API-gegevens veilig opgeslagen",
    "toast.defaultUpdated": "Standaardaccount bijgewerkt",
    "toast.emptyMessage": "Bericht mag niet leeg zijn",
    "toast.enterName": "Voer een naam in",
    "toast.error": "Er ging iets mis",
    "toast.futureTime": "Kies een tijd in de toekomst",
    "toast.importWaOnly": "Bulkimport is voorlopig alleen voor WhatsApp",
    "toast.logout": "Uitgelogd",
    "toast.mediaScheduled": "Media gepland",
    "toast.mediaSent": "Media verzonden",
    "toast.pickDateTime": "Selecteer datum en tijd",
    "toast.pickRecipient": "Selecteer een ontvanger",
    "toast.randomScheduled": "Dagelijks willekeurig bericht gepland · eerste: {when}",
    "toast.refreshed": "Vernieuwd",
    "toast.retried": "Opnieuw gepland",
    "toast.selectChatFirst": "Selecteer eerst een chat",
    "toast.telegramLogout": "Uitgelogd bij Telegram",
    "toast.templateSaved": "Sjabloon opgeslagen",
    "toast.titleRequired": "Titel en bericht verplicht",
    "toast.waDisconnected": "WhatsApp verbroken",
    "toast.webhookAdded": "Webhook toegevoegd",
    "toast.whatsappConnected": "WhatsApp verbonden! Berichten synchroniseren…",
    "toast.writeForSchedule": "Schrijf een bericht om te plannen",
    "toast.writeMessage": "Schrijf een bericht",
}

PHRASES = [
    ("Konto hinzufügen", "Account toevoegen"),
    ("+ Konto hinzufügen", "+ Account toevoegen"),
    ("Konto", "Account"),
    ("konto", "account"),
    ("Konten", "Accounts"),
    ("konten", "accounts"),
    ("Verbinden", "Verbinden"),
    ("Trennen", "Verbreken"),
    ("trennen", "verbreken"),
    ("Abmelden", "Uitloggen"),
    ("abmelden", "uitloggen"),
    ("Verwalten", "Beheren"),
    ("Hinzufügen", "Toevoegen"),
    ("Zurück", "Terug"),
    ("Abbrechen", "Annuleren"),
    ("Schließen", "Sluiten"),
    ("Weiter", "Doorgaan"),
    ("Löschen", "Verwijderen"),
    ("Erledigt", "Klaar"),
    ("Los", "Gaan"),
    ("Laden…", "Laden…"),
    ("Nein", "Nee"),
    ("Ja", "Ja"),
    ("Aktualisieren", "Vernieuwen"),
    ("Entfernen", "Verwijderen"),
    ("Speichern", "Opslaan"),
    ("Suchen", "Zoeken"),
    ("Senden", "Versturen"),
    ("Überspringen", "Overslaan"),
    ("Planen", "Plannen"),
    ("Neue Nachricht", "Nieuw bericht"),
    ("Nachricht", "Bericht"),
    ("nachricht", "bericht"),
    ("Nachrichten", "Berichten"),
    ("nachrichten", "berichten"),
    ("Vorlage", "Sjabloon"),
    ("Vorlagen", "Sjablonen"),
    ("vorlage", "sjabloon"),
    ("Heute", "Vandaag"),
    ("Gestern", "Gisteren"),
    ("Morgen", "Morgen"),
    ("Sprache", "Taal"),
    ("Passwort", "Wachtwoord"),
    ("passwort", "wachtwoord"),
    ("Benutzername", "Gebruikersnaam"),
    ("Anmelden", "Inloggen"),
    ("Geplant", "Gepland"),
    ("Ausstehend", "In afwachting"),
    ("Gesendet", "Verzonden"),
    ("Fehlgeschlagen", "Mislukt"),
    ("Verbunden", "Verbonden"),
    ("Getrennt", "Verbroken"),
    ("Aktiv", "Actief"),
    ("Inaktiv", "Inactief"),
    ("Wählen Sie", "Selecteer"),
    ("wählen Sie", "selecteer"),
    ("Geben Sie", "Voer"),
    ("geben Sie", "voer"),
    ("Schreiben Sie", "Schrijf"),
    ("schreiben Sie", "schrijf"),
    ("Verknüpfen Sie", "Koppel"),
    ("verknüpfen Sie", "koppel"),
    ("Scannen Sie", "Scan"),
    ("scannen Sie", "scan"),
    ("Öffnen Sie", "Open"),
    ("Datei anhängen", "Bestand bijvoegen"),
    ("Umbenennen", "Hernoemen"),
    ("Ungelesen", "Ongelezen"),
    ("Privat", "Privé"),
    ("Gruppen", "Groepen"),
    ("Kanäle", "Kanalen"),
    ("Kontakte", "Contacten"),
    ("Importieren", "Importeren"),
    ("Synchronisieren", "Synchroniseren"),
    ("Verlauf", "Geschiedenis"),
    ("verlauf", "geschiedenis"),
    ("Dokumentation", "Documentatie"),
    ("Entwickler", "Ontwikkelaar"),
    ("Verbindung", "Verbinding"),
    ("Schnelle Aktionen", "Snelle acties"),
    ("Zeitzone", "Tijdzone"),
    ("Stornieren", "Annuleren"),
    ("Benutzerdefiniert", "Aangepast"),
    ("Täglich", "Dagelijks"),
    ("Stündlich", "Elk uur"),
    ("Wöchentlich", "Wekelijks"),
    ("Einmalig", "Eenmalig"),
    ("Einmal", "Eenmalig"),
    ("Andere", "Overig"),
    ("Kontakt", "Contact"),
    ("Gruppe", "Groep"),
    ("Kanal", "Kanaal"),
    ("Menü", "Menu"),
    ("Hauptmenü", "Hoofdmenu"),
    ("Anzeigename", "Weergavenaam"),
    ("Nummer", "Nummer"),
    ("Datum", "Datum"),
    ("Zeit", "Tijd"),
    ("Beginn", "Start"),
    ("Ende", "Einde"),
    ("Intervall", "Interval"),
    ("Minuten", "minuten"),
    ("Stunde", "uur"),
    ("Stunden", "uren"),
    ("Uhr", "uur"),
    ("Jetzt senden", "Nu versturen"),
    ("Jetzt verbinden", "Nu verbinden"),
    ("Bereits verbunden!", "Al verbonden!"),
    ("Gelöscht", "Verwijderd"),
    ("Gespeichert", "Opgeslagen"),
    ("Abgebrochen", "Geannuleerd"),
    ("Ihr ", "Je "),
    ("Ihre ", "Je "),
    ("Ihren ", "Je "),
    ("Ihrem ", "Je "),
    ("Ihrer ", "Je "),
    ("Sie ", "Je "),
    (" sie ", " je "),
]


def de_to_nl(text: str) -> str:
    out = text
    for a, b in PHRASES:
        out = out.replace(a, b)
    return out


def main() -> None:
    nl: dict[str, str] = {}
    for key, value in DE.items():
        nl[key] = KEY_OVERRIDES.get(key, de_to_nl(value))
    # Polish remaining German formal address
    for key, value in list(nl.items()):
        nl[key] = value.replace("z.B.", "bijv.").replace("Mama", "Mama")
    (SRC_ROOT / "locales/nl.json").write_text(
        json.dumps(nl, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    en = json.loads((SRC_ROOT / "locales/en.json").read_text(encoding="utf-8"))
    same = sum(1 for k in en if nl[k] == en[k])
    print(f"nl: {len(en)-same}/{len(en)} translated")


if __name__ == "__main__":
    main()
